language: go

os:
  - linux
  
go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"

matrix:
  include:
    - os: linux
      name: "GolangCI-Lint"
      dist: xenial
      go: 1.12.x
      script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
        - golangci-lint run rticonnextdds_connector.go rticonnextdds_connector_test.go 

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install git-lfs; fi
    
before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then git lfs pull; fi

script:
  - cd $TRAVIS_BUILD_DIR; bash run_test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
